version: '3'
services:
  gitinpired-rw-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: gitinpired-rw-backend
    container_name: gitinpired-rw-backend
    ports:
      - '4501:4501'
    restart: on-failure
    volumes:
      - './.data:/app/submissions'
